name: Python Script Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Instalacao Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - name: Instalacao de dependencias Python 
        run: python -m pip install --upgrade pip requests
      - name: Execucao Script Python
        run: |
          python testes.py
